version: '2'
services:
  django:
    image :  python:3.11
    volumes:
      - ./:/app
    ports: 
      - 8000:8000
      
      

    working_dir: /app  # Set the working directory to /app
    command: /app/init.sh  # Run the custom initialization script
    

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    networks:
      - efk
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    ports:
      - 5601:5601
    networks:
      - efk
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.8.0
    user: root
    volumes:
      - C:\Users\chesh\allprojects\gslprojelk\filebeat.yml:/usr/share/filebeat/filebeat.yml
      - C:\Users\chesh\allprojects\gslprojelk\logs:/usr/share/filebeat/logs
    entrypoint: ["sh", "-c", "chmod go-w /usr/share/filebeat/filebeat.yml && filebeat -e"]

    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - efk
    links:
      - kibana
      - elasticsearch
    depends_on:
      - elasticsearch
networks:
  efk:
    driver: bridge